id: AF0727310
base_file: f556B.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:54:52.092499
  last_modified_at: 2022-06-17 12:54:52.092504
