id: AF0727310
base_file: f3483.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:54:52.087114
  last_modified_at: 2022-06-17 12:54:52.087120
